const path = require('path');

function getFileName(fileExtension) {
// Almost random, random filename generator 0_*
// This function returns a filename that is generated by creating a random string of characters using Date.now() and Math.random and then randomizing that string by splitting and sorting the string randomly with the provided fileExtension appended

   var sometext = (
      Date.now() + Math.random().toString(36).substring(7)
   ).split('').sort(function () {
      return 0.5 - Math.random()
   }).join('');
   
   return sometext + "." + fileExtension;

}

const buildPaths = {
   buildPathdynamicHtml: path.resolve('./input/dynamicbuild.html'),
   buildPathstaticHtml: path.resolve('./input/static.html'),
   buildPathPdf: path.resolve("./out/", getFileName("pdf"))
};

module.exports = buildPaths;


